// Stage 6.3: the single source of pacing truth for the V2_ONLY engine.
//
// Model (facts, see docs2/subsystems/TIMING_MODEL.md):
//   - LOGICAL TICK: generated by the vsync-wait loop itself (sub_10130
//     mirror) — one v2_render_callback per iteration; NOT wall-clock ISR.
//     A game frame consumes 3 ticks (3 page-flip waits): the three sub-frames
//     of the DOS game, each shown for one 60 Hz refresh of Mode X (the camera
//     and the sprites move on every one of them). Replays/goldens depend only
//     on tick COUNTS, never on wall time (headless runs the same loop unpaced).
//   - PACING (2026-09-11): each tick waits for the DISPLAY's vsync, handed over
//     by the presenter on the 60 Hz schedule of its refreshes (render_v2.cpp,
//     v2_vsync_wait_game) — the game's flips and the display's frames run in
//     lockstep as on the VGA. Without a real vsync the tick is a 60.0 Hz timer.
//   - PRESENTATION (2026-09-15): the MAIN thread is the presenter of the game
//     build (the SDL events, the vsync latch, the frame, the present); the
//     simulation runs in its own thread and publishes a snapshot at every flip
//     (v2_smooth.cpp) — the presenter composes every frame it shows from the
//     newest snapshot right before each refresh; SMOOTH interpolates between
//     the two newest flips for displays whose refresh is no multiple of 60.
//     (The test build keeps its render thread beside the orig and mirror threads.)
#pragma once
#include <SDL2/SDL.h>
#include <cstdlib>
#include <cstdint>

// The VGA refresh of Mode X 320x240: the tick period when no display vsync is available.
static const double V2_TICK_HZ = 60.0;
// Presenter pacing (the compose + blit cadence) without a vsync present.
static const uint32_t V2_PRESENT_MS = 15;
// Main-loop frame budget (outer pacing target; the wait loops inside the
// phases dominate, so this mostly bounds menu/idle spins).
static const uint32_t V2_FRAME_BUDGET_MS = 16;

extern bool v2_vsync_wait_game(void);   // render_v2.cpp: true = a display vsync was waited for (the lock)
#include <atomic>
#include <cstdint>
// FRAME DELAY (2026-09-15, v2_vm.cpp v2_frame_delay_sleep): the game's frame start — the input read
// of pre-VM and the VM — moved as close to render1's vsync as the frame's work allows, so a key
// pressed during the previous frame's waits is read later and shown at the same vsync (the
// game reads input once per 50 ms frame and reacts in that frame: the read-to-flip part of the
// latency, one refresh today, shrinks by the delay). Inputs from render_v2.cpp:
extern std::atomic<uint64_t> v2_vs_last_wake;       // when the game's last vsync wait returned
extern std::atomic<uint32_t> v2_vs_pending;         // waits that found their vsync already fired (the game was late)
extern double v2_vsync_game_period_ms(void);        // the period between the game's vsyncs (0: no lock or an uneven schedule)
extern double v2_presenter_latch_margin_ms(void);   // how long before a refresh the presenter latches
#include <atomic>
extern std::atomic<uint64_t> v2_tick_wait_ticks;   // render_v2.cpp: performance-counter ticks the game thread spent in these waits (STATS: frame work = frame - waits)
static inline void v2_tick_sleep(void) {
#if defined(V2_ONLY) && !defined(HEADLESS)
    // V2_NOVSYNC=1 drops the game-thread tick pacing too (the presenter
    // loop honors the same env in v2_main.cpp) — a windowed V2_ONLY replay
    // then runs at CPU speed for benchmarking/A-B trace runs. Frame-based
    // determinism (tick counters, V2_AIL_FRAME_TICKS) is pacing-independent.
    static int novsync = -1;
    if (novsync < 0) { const char* e = getenv("V2_NOVSYNC"); novsync = (e && *e == '1') ? 1 : 0; }
    if (novsync) return;
    struct WaitClock { uint64_t t0; WaitClock() : t0(SDL_GetPerformanceCounter()) {} ~WaitClock() { v2_tick_wait_ticks.fetch_add(SDL_GetPerformanceCounter() - t0, std::memory_order_relaxed); } } clock;
    if (v2_vsync_wait_game()) return;            // the display's vsync
    // no lock (no blocking present, or the presenter stalled): a 60.0 Hz timer
    // on a running deadline, so the period is exact on average (SDL_Delay(16)
    // ran 16.3 ms and beat against the display); restarted after a stall
    static uint64_t deadline = 0;
    const uint64_t freq = SDL_GetPerformanceFrequency(), now = SDL_GetPerformanceCounter();
    const uint64_t period = (uint64_t)((double)freq / V2_TICK_HZ);
    if (deadline == 0 || now > deadline + 3 * period) deadline = now;
    deadline += period;
    if (deadline > now) {
        const uint64_t left_ms = (deadline - now) * 1000 / freq;
        if (left_ms > 1) SDL_Delay((Uint32)(left_ms - 1));
        while (SDL_GetPerformanceCounter() < deadline) SDL_Delay(0);
    }
#endif
}

extern bool v2_present_vsync;   // render_v2.cpp: the presenter's SDL_RenderPresent blocks on vsync (UX stage 9)
static inline void v2_present_sleep(void) {
    // Same V2_NOVSYNC gate as the tick pacing (a CPU-speed replay needs the
    // presenter spinning too). UX stage 9: with a vsync presenter the present
    // call itself paces the loop at the display refresh — no extra sleep.
    static int novsync = -1;
    if (novsync < 0) { const char* e = getenv("V2_NOVSYNC"); novsync = (e && *e == '1') ? 1 : 0; }
    if (novsync) SDL_Delay(1);   // fast pacing, not a spin (shutdown races, contention)
    else if (!v2_present_vsync) SDL_Delay(V2_PRESENT_MS);
}

// (The interpolation lives in v2_smooth.cpp since UX stage 9; reworked
// 2026-09-11 to interpolate between the two newest FLIPS — the sub-frames —
// under the SMOOTH < NONE | AUTO | ON > option, AUTO = only on a display whose
// refresh is no multiple of 60 Hz. v2_smooth_effective() says whether the
// presenter is interpolating right now.)
