// Stage 6.3: the single source of pacing truth for the V2_ONLY engine.
//
// Model (facts, see docs2/subsystems/TIMING_MODEL.md):
//   - LOGICAL TICK: generated by the vsync-wait loop itself (sub_10130
//     mirror) — one v2_render_callback per iteration; NOT wall-clock ISR.
//     A game frame consumes 3 ticks (3 page-flip waits) ≈ 3×16 ms ≈ the
//     DOS-observed ~53 ms cadence. Replays/goldens depend only on tick
//     COUNTS, never on wall time (headless runs the same loop unpaced).
//   - PRESENTATION: a separate thread snapshots the draw buffer and blits
//     it at its own rate — already decoupled from the game frame rate.
//   - INTERPOLATION: an explicit extension point, OFF by default and not
//     implemented; the presenter shows the last completed frame as-is.
#pragma once
#include <SDL2/SDL.h>
#include <cstdlib>

// Logical tick pacing (interactive builds only; headless never sleeps).
static const uint32_t V2_TICK_MS = 16;      // vsync-wait iteration pacing
// Presenter thread pacing (snapshot + blit cadence).
static const uint32_t V2_PRESENT_MS = 15;
// Main-loop frame budget (outer pacing target; the wait loops inside the
// phases dominate, so this mostly bounds menu/idle spins).
static const uint32_t V2_FRAME_BUDGET_MS = 16;

static inline void v2_tick_sleep(void) {
#if defined(V2_ONLY) && !defined(HEADLESS)
    // V2_NOVSYNC=1 drops the game-thread tick pacing too (the presenter
    // loop honors the same env in v2_main.cpp) — a windowed V2_ONLY replay
    // then runs at CPU speed for benchmarking/A-B trace runs. Frame-based
    // determinism (tick counters, V2_AIL_FRAME_TICKS) is pacing-independent.
    static int novsync = -1;
    if (novsync < 0) { const char* e = getenv("V2_NOVSYNC"); novsync = (e && *e == '1') ? 1 : 0; }
    if (!novsync) SDL_Delay(V2_TICK_MS);
#endif
}

static inline void v2_present_sleep(void) {
    // Same V2_NOVSYNC gate as the tick pacing: the presenter drives
    // vsync_count, so every blocking wait-loop iteration is bounded by this
    // sleep — a CPU-speed replay needs the presenter spinning too.
    static int novsync = -1;
    if (novsync < 0) { const char* e = getenv("V2_NOVSYNC"); novsync = (e && *e == '1') ? 1 : 0; }
    if (!novsync) SDL_Delay(V2_PRESENT_MS);
    else SDL_Delay(1);   // fast pacing, not a spin (shutdown races, contention)
}

// Interpolation extension point (roadmap 6.3: optional, OFF by default).
// When somebody implements it, the presenter would blend the last two
// stable buffers by the tick phase; until then this stays a documented
// no-op switch so callers have ONE place to look at.
static inline int v2_interpolation_enabled(void) { return 0; }
