#!/usr/bin/env python3
"""Declarations of every v2_vm.cpp function the generated executors call
(src/sdl/gen/v2_vm_gen_decls.gen.inc, included by v2_vm_gen.h).

The executors (chunk_01cN.gen.inc / anim_01cN.gen.inc) are compiled in their
own translation units (src/sdl/gen/exec_01cN.cpp), so the v2_vm.cpp helpers
they call — the op handlers, the collision/search/probe cores, the dump and
trace hooks — must have external linkage and a declaration here. This tool
derives the list from the generated files, takes each signature from its
first declaration or definition in v2_vm.cpp, and refuses a helper that is
still `static` there.

  gen_vm_decls.py          -> rewrites src/sdl/gen/v2_vm_gen_decls.gen.inc
  gen_vm_decls.py --check  -> exit 1 when the file is stale (CI / pre-commit)"""
import re, glob, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
VM = os.path.join(ROOT, 'src/sdl/v2_vm.cpp')
OUT = os.path.join(ROOT, 'src/sdl/gen/v2_vm_gen_decls.gen.inc')
# hooks the executor macros (G_PRE/G_POST/V2_GEN_HASHSNAP) use besides what the
# instruction bodies name
EXTRA = {'v2_ds_hash', 'v2_obj_hash', 'v2_pcdump_note', 'v2_animdump_note'}

def build():
    t = open(VM).read()
    used = set()
    for f in glob.glob(os.path.join(ROOT, 'src/sdl/gen/*.gen.inc')):
        if f.endswith('v2_vm_gen_decls.gen.inc'):
            continue
        used |= set(re.findall(r'\b(v2_\w+)\b', open(f, errors='ignore').read()))
    # every function v2_vm.cpp declares or defines at file scope
    fn_re = re.compile(r'^(static\s+)?((?:[\w:<>\*&]+\s+)*?\*?)(v2_\w+)\s*\(', re.M)
    first = {}
    for m in fn_re.finditer(t):
        name = m.group(3)
        if name in used or name in EXTRA:
            if m.group(1):
                raise SystemExit(f'{name} is still static in v2_vm.cpp — the executors call it')
            first.setdefault(name, m)
    names = sorted(n for n in first if n in used or n in EXTRA)
    lines = ["// AUTO-GENERATED by tools/data/gen_vm_decls.py — declarations of the v2_vm.cpp",
             "// functions the generated executors call. Do not edit — regenerate."]
    for n in names:
        m = first[n]
        p = t.index('(', m.end() - 1); depth = 0; q = p
        while True:
            c = t[q]
            if c == '(': depth += 1
            elif c == ')':
                depth -= 1
                if depth == 0: break
            q += 1
        d = re.sub(r'\s+', ' ', t[m.start(2):q + 1]).strip()
        d = re.sub(r'\s*/\*.*?\*/', '', d)
        if '=' in d:
            raise SystemExit(f'{n}: default argument in the signature — declare it by hand')
        lines.append(d + ';')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    text = build()
    if '--check' in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ''
        sys.exit(0 if cur == text else 1)
    open(OUT, 'w').write(text)
    print(f'{OUT}: {text.count(chr(10)) - 2} declarations')
