#!/usr/bin/env python3
"""Stage 3A: transpile a template chunk's object bytecode to C++.

Emits src/sdl/gen/chunk_XXXX.gen.inc — included from v2_vm.cpp (same TU,
so the static v2_vm_op_* handlers are directly callable). The generated
function replaces ONLY the fetch-decode loop: every instruction becomes
a direct call to its verified handler with vm.pc pre-set past the opcode
byte (handlers read their own operands from the chunk stream exactly as
under the VM), followed by statically-known control flow:

  fall  -> goto next label
  br    -> if (vm.pc == TGT) goto TGT else goto FALL
  srch  -> 3-way (TGT / continuation / skip)
  jmp   -> goto TGT (05 call-jump included; ALT_PC returns re-enter the
           dispatch switch because 06 loads a dynamic pc)
  stop  -> running=false -> return (yield/exit/despawn), or 06: continue

Unknown pc (dead code the STRICT walker cannot see, future dyn) falls
back to the interpreter loop: the function returns false and the caller
resumes the classic while-loop seamlessly (vm state is always coherent).

Verify parity: the G_PRE/G_POST macros in v2_vm.cpp reproduce the exact
per-opcode side channels of the loop (si_track seed, hash-before snaps,
trace_record_v2_ext, the per-slot trace ring) so a gencode binary stays
comparable against the real side inside the standard headless canon.

Usage: gen_transpile.py CHUNK_HEX [outdir]
"""
import sys, re, struct, importlib.util, os

def load(n, p):
    sp = importlib.util.spec_from_file_location(n, p)
    m = importlib.util.module_from_spec(sp)
    sp.loader.exec_module(m)
    return m

lf = load('lf', 'tools/data/lvs_full.py')
dz = lf.dz
dc = lf.dc
ex = load('ex', 'tools/data/expr.py')

def handler_map():
    src = open('src/sdl/v2_vm.cpp').read()
    tbl = {}
    for m in re.finditer(r'v2_vm_optable\[0x([0-9A-Fa-f]{2})\]\s*=\s*(\w+);', src):
        tbl[int(m.group(1), 16)] = m.group(2)
    return tbl

def transpile(cid, outdir='src/sdl/gen'):
    d, seen, table = lf.full_walk(cid)
    tbl = handler_map()
    LAY = dz.load_layout_names()
    lines = []
    w = lines.append
    w(f'// AUTO-GENERATED by tools/data/gen_transpile.py from chunk 0x{cid:X}.')
    w(f'// {len(seen)} instructions. Do not edit — regenerate.')
    w(f'static bool v2_gen_exec_{cid:x}(V2VM& vm, int& max_ops) {{')
    w('    uint16_t g_last_pc = 0xFFFF;   // diagnostics: last executed insn')
    w('    (void)g_last_pc;')
    w('    while (vm.running) {')
    w('        switch (vm.pc) {')
    for pc in sorted(seen):
        w(f'        case 0x{pc:04X}: goto L_{pc:04X};')
    w('        default:')
    w('            { static int _gdbg = 0; if (_gdbg < 20) { _gdbg++;')
    w('              fprintf(stderr, "V2-GEN-FALLBACK: pc=%04X after insn %04X '
      'obj=%02X\\n", vm.pc, g_last_pc, vm.obj); } }')
    w('            return false;   // unknown pc -> interpreter fallback')
    w('        }')
    # Instruction blocks. Control flow trusts ONLY vm.pc: after every
    # handler we re-enter the dispatch switch (`continue`). Handlers own
    # their pc semantics — including dynamic ones the static model cannot
    # prove (2D/36 search continuations jump via DS_SEARCH_JUMP, 06 loads
    # ALT_PC). What dies versus the interpreter is the fetch+decode+table
    # dispatch; static goto shortcuts can come back later per proven op.
    for pc in sorted(seen):
        op = seen[pc][0]
        ln, kind, tgt = dc.decode_info(d, pc, op, table)
        h = tbl.get(op)
        if h is None:
            raise SystemExit(f'no handler for op {op:02X}')
        ob_end = pc + ln - (2 if (kind in ('br', 'jmp', 'srch') and tgt is not None) else 0)
        body = d[pc+1:ob_end]
        e = ex.render(op, body, LAY)
        cmt = f'  // {e}' if e else ''
        w(f'    L_{pc:04X}:')
        w(f'        g_last_pc = 0x{pc:04X};')
        w(f'        G_PRE(0x{pc:04X}, 0x{op:02X});')
        w(f'        {h}(vm);{cmt}')
        w(f'        G_POST(0x{pc:04X}, 0x{op:02X});')
        w('        continue;')
    w('    }')
    w('    return true;')
    w('}')
    os.makedirs(outdir, exist_ok=True)
    path = f'{outdir}/chunk_{cid:04x}.gen.inc'
    open(path, 'w').write('\n'.join(lines) + '\n')
    print(f'{path}: {len(lines)} lines, {len(seen)} instructions')
    return path

if __name__ == '__main__':
    cid = int(sys.argv[1], 16)
    outdir = sys.argv[2] if len(sys.argv) > 2 else 'src/sdl/gen'
    transpile(cid, outdir)
