#!/usr/bin/env python3
"""Linear SPC700 disassembler (UX stage 10: the SNES DE sound driver).
Usage: spc700_dis.py <bin> <load_addr_hex> <from_hex> <len_hex>
Operand notation follows the usual SPC700 assemblers (dp = direct page,
!abs = absolute, #imm, r = relative)."""
import sys

# opcode -> (mnemonic with operand template, operand byte count, operand kinds)
# kinds: d dp, D dp (second, for dp,dp forms: order in bytes is src then dst),
# i imm8, a abs16, r rel8, m mem-bit (abs13.bit), n dp+rel (for cbne/dbnz dp,r)
T = {}
def op(code, text, size, kinds=""): T[code] = (text, size, kinds)
# --- generated by hand from the SPC700 opcode matrix ---
rows = """
00 NOP 0 |01 TCALL 0 0 |02 SET1 d.0 1 d|03 BBS d.0,r 2 dr|04 OR A,d 1 d|05 OR A,!a 2 a|06 OR A,(X) 0|07 OR A,[d+X] 1 d|08 OR A,#i 1 i|09 OR d,D 2 Dd|0A OR1 C,m 2 m|0B ASL d 1 d|0C ASL !a 2 a|0D PUSH PSW 0|0E TSET1 !a 2 a|0F BRK 0
10 BPL r 1 r|11 TCALL 1 0|12 CLR1 d.0 1 d|13 BBC d.0,r 2 dr|14 OR A,d+X 1 d|15 OR A,!a+X 2 a|16 OR A,!a+Y 2 a|17 OR A,[d]+Y 1 d|18 OR d,#i 2 id|19 OR (X),(Y) 0|1A DECW d 1 d|1B ASL d+X 1 d|1C ASL A 0|1D DEC X 0|1E CMP X,!a 2 a|1F JMP [!a+X] 2 a
20 CLRP 0|21 TCALL 2 0|22 SET1 d.1 1 d|23 BBS d.1,r 2 dr|24 AND A,d 1 d|25 AND A,!a 2 a|26 AND A,(X) 0|27 AND A,[d+X] 1 d|28 AND A,#i 1 i|29 AND d,D 2 Dd|2A OR1 C,/m 2 m|2B ROL d 1 d|2C ROL !a 2 a|2D PUSH A 0|2E CBNE d,r 2 dr|2F BRA r 1 r
30 BMI r 1 r|31 TCALL 3 0|32 CLR1 d.1 1 d|33 BBC d.1,r 2 dr|34 AND A,d+X 1 d|35 AND A,!a+X 2 a|36 AND A,!a+Y 2 a|37 AND A,[d]+Y 1 d|38 AND d,#i 2 id|39 AND (X),(Y) 0|3A INCW d 1 d|3B ROL d+X 1 d|3C ROL A 0|3D INC X 0|3E CMP X,d 1 d|3F CALL !a 2 a
40 SETP 0|41 TCALL 4 0|42 SET1 d.2 1 d|43 BBS d.2,r 2 dr|44 EOR A,d 1 d|45 EOR A,!a 2 a|46 EOR A,(X) 0|47 EOR A,[d+X] 1 d|48 EOR A,#i 1 i|49 EOR d,D 2 Dd|4A AND1 C,m 2 m|4B LSR d 1 d|4C LSR !a 2 a|4D PUSH X 0|4E TCLR1 !a 2 a|4F PCALL u 1 i
50 BVC r 1 r|51 TCALL 5 0|52 CLR1 d.2 1 d|53 BBC d.2,r 2 dr|54 EOR A,d+X 1 d|55 EOR A,!a+X 2 a|56 EOR A,!a+Y 2 a|57 EOR A,[d]+Y 1 d|58 EOR d,#i 2 id|59 EOR (X),(Y) 0|5A CMPW YA,d 1 d|5B LSR d+X 1 d|5C LSR A 0|5D MOV X,A 0|5E CMP Y,!a 2 a|5F JMP !a 2 a
60 CLRC 0|61 TCALL 6 0|62 SET1 d.3 1 d|63 BBS d.3,r 2 dr|64 CMP A,d 1 d|65 CMP A,!a 2 a|66 CMP A,(X) 0|67 CMP A,[d+X] 1 d|68 CMP A,#i 1 i|69 CMP d,D 2 Dd|6A AND1 C,/m 2 m|6B ROR d 1 d|6C ROR !a 2 a|6D PUSH Y 0|6E DBNZ d,r 2 dr|6F RET 0
70 BVS r 1 r|71 TCALL 7 0|72 CLR1 d.3 1 d|73 BBC d.3,r 2 dr|74 CMP A,d+X 1 d|75 CMP A,!a+X 2 a|76 CMP A,!a+Y 2 a|77 CMP A,[d]+Y 1 d|78 CMP d,#i 2 id|79 CMP (X),(Y) 0|7A ADDW YA,d 1 d|7B ROR d+X 1 d|7C ROR A 0|7D MOV A,X 0|7E CMP Y,d 1 d|7F RET1 0
80 SETC 0|81 TCALL 8 0|82 SET1 d.4 1 d|83 BBS d.4,r 2 dr|84 ADC A,d 1 d|85 ADC A,!a 2 a|86 ADC A,(X) 0|87 ADC A,[d+X] 1 d|88 ADC A,#i 1 i|89 ADC d,D 2 Dd|8A EOR1 C,m 2 m|8B DEC d 1 d|8C DEC !a 2 a|8D MOV Y,#i 1 i|8E POP PSW 0|8F MOV d,#i 2 id
90 BCC r 1 r|91 TCALL 9 0|92 CLR1 d.4 1 d|93 BBC d.4,r 2 dr|94 ADC A,d+X 1 d|95 ADC A,!a+X 2 a|96 ADC A,!a+Y 2 a|97 ADC A,[d]+Y 1 d|98 ADC d,#i 2 id|99 ADC (X),(Y) 0|9A SUBW YA,d 1 d|9B DEC d+X 1 d|9C DEC A 0|9D MOV X,SP 0|9E DIV YA,X 0|9F XCN A 0
A0 EI 0|A1 TCALL 10 0|A2 SET1 d.5 1 d|A3 BBS d.5,r 2 dr|A4 SBC A,d 1 d|A5 SBC A,!a 2 a|A6 SBC A,(X) 0|A7 SBC A,[d+X] 1 d|A8 SBC A,#i 1 i|A9 SBC d,D 2 Dd|AA MOV1 C,m 2 m|AB INC d 1 d|AC INC !a 2 a|AD CMP Y,#i 1 i|AE POP A 0|AF MOV (X)+,A 0
B0 BCS r 1 r|B1 TCALL 11 0|B2 CLR1 d.5 1 d|B3 BBC d.5,r 2 dr|B4 SBC A,d+X 1 d|B5 SBC A,!a+X 2 a|B6 SBC A,!a+Y 2 a|B7 SBC A,[d]+Y 1 d|B8 SBC d,#i 2 id|B9 SBC (X),(Y) 0|BA MOVW YA,d 1 d|BB INC d+X 1 d|BC INC A 0|BD MOV SP,X 0|BE DAS A 0|BF MOV A,(X)+ 0
C0 DI 0|C1 TCALL 12 0|C2 SET1 d.6 1 d|C3 BBS d.6,r 2 dr|C4 MOV d,A 1 d|C5 MOV !a,A 2 a|C6 MOV (X),A 0|C7 MOV [d+X],A 1 d|C8 CMP X,#i 1 i|C9 MOV !a,X 2 a|CA MOV1 m,C 2 m|CB MOV d,Y 1 d|CC MOV !a,Y 2 a|CD MOV X,#i 1 i|CE POP X 0|CF MUL YA 0
D0 BNE r 1 r|D1 TCALL 13 0|D2 CLR1 d.6 1 d|D3 BBC d.6,r 2 dr|D4 MOV d+X,A 1 d|D5 MOV !a+X,A 2 a|D6 MOV !a+Y,A 2 a|D7 MOV [d]+Y,A 1 d|D8 MOV d,X 1 d|D9 MOV d+Y,X 1 d|DA MOVW d,YA 1 d|DB MOV d+X,Y 1 d|DC DEC Y 0|DD MOV A,Y 0|DE CBNE d+X,r 2 dr|DF DAA A 0
E0 CLRV 0|E1 TCALL 14 0|E2 SET1 d.7 1 d|E3 BBS d.7,r 2 dr|E4 MOV A,d 1 d|E5 MOV A,!a 2 a|E6 MOV A,(X) 0|E7 MOV A,[d+X] 1 d|E8 MOV A,#i 1 i|E9 MOV X,!a 2 a|EA NOT1 m 2 m|EB MOV Y,d 1 d|EC MOV Y,!a 2 a|ED NOTC 0|EE POP Y 0|EF SLEEP 0
F0 BEQ r 1 r|F1 TCALL 15 0|F2 CLR1 d.7 1 d|F3 BBC d.7,r 2 dr|F4 MOV A,d+X 1 d|F5 MOV A,!a+X 2 a|F6 MOV A,!a+Y 2 a|F7 MOV A,[d]+Y 1 d|F8 MOV X,d 1 d|F9 MOV X,d+Y 1 d|FA MOV d,D 2 Dd|FB MOV Y,d+X 1 d|FC INC Y 0|FD MOV Y,A 0|FE DBNZ Y,r 1 r|FF STOP 0
"""
for line in rows.strip().splitlines():
    for cell in line.split("|"):
        parts = cell.split()
        code = int(parts[0], 16); size = int(parts[-1]) if parts[-1].isdigit() else None
        if size is None:  # form: CODE TEXT... SIZE KINDS
            size = int(parts[-2]); kinds = parts[-1]; text = " ".join(parts[1:-2])
        else:
            kinds = ""; text = " ".join(parts[1:-1])
        T[code] = (text, size, kinds)

def fmt(text, kinds, ops, pc):
    # substitute operand placeholders by kind order in the byte stream
    out = text
    if kinds == "d": out = out.replace("d", f"${ops[0]:02X}", 1)
    elif kinds == "i": out = out.replace("#i", f"#${ops[0]:02X}").replace(" u", f" ${ops[0]:02X}")
    elif kinds == "a": out = out.replace("!a", f"!${ops[0] | (ops[1] << 8):04X}")
    elif kinds == "r": out = out.replace(" r", f" ${(pc + 2 + (ops[0] - 256 if ops[0] > 127 else ops[0])) & 0xFFFF:04X}")
    elif kinds == "dr":
        tgt = (pc + 3 + (ops[1] - 256 if ops[1] > 127 else ops[1])) & 0xFFFF
        out = out.replace("d", f"${ops[0]:02X}", 1).replace(",r", f",${tgt:04X}")
    elif kinds == "id": out = out.replace("d,#i", f"${ops[1]:02X},#${ops[0]:02X}")
    elif kinds == "Dd": out = out.replace("d,D", f"${ops[1]:02X},${ops[0]:02X}")
    elif kinds == "m":
        v = ops[0] | (ops[1] << 8); out = out.replace("m", f"!${v & 0x1FFF:04X}.{v >> 13}")
    return out

def disasm(mem, load, start, length):
    pc = start; end = start + length
    while pc < end:
        code = mem[pc - load]
        text, size, kinds = T[code]
        ops = [mem[pc - load + 1 + k] for k in range(size)]
        hexs = " ".join(f"{b:02X}" for b in mem[pc - load:pc - load + 1 + size])
        print(f"{pc:04X}  {hexs:<9} {fmt(text, kinds, ops, pc)}")
        pc += 1 + size

if __name__ == "__main__":
    mem = open(sys.argv[1], "rb").read()
    load = int(sys.argv[2], 16); start = int(sys.argv[3], 16); length = int(sys.argv[4], 16)
    disasm(mem, load, start, length)
